name: "Build Alpha"

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check Out"
        uses: actions/checkout@v4
      - name: 上傳檔案
        uses: actions/upload-artifact@v3
        with:
          name: FigmaTW-alpha
          path: ./extension/*
